### Compare,Pivoting & Melting

In [2]:
import pandas as pd

### Compare

In [10]:
shop_7Sep={
    "Fruites":["Mango","Apple","Banana","Papaya"],
    "Prices":[100,150,60,30],
    "Quantity":[10,8,12,14]
}

stock_7Sep=pd.DataFrame(shop_7Sep)

shop_8Sep={
    "Fruites":["Mango","Apple","Banana","Papaya"],
    "Prices":[120,200,60,35],
    "Quantity":[15,6,24,17]
}

stock_8Sep=pd.DataFrame(shop_8Sep)

stock_7Sep.compare(stock_8Sep)
stock_7Sep.compare(stock_8Sep,align_axis=0)
stock_7Sep.compare(stock_8Sep,keep_shape=True)
stock_7Sep.compare(stock_8Sep,keep_equal=True)
stock_7Sep.compare(stock_8Sep,align_axis=0,keep_equal=True,keep_shape=True)

        Fruites  Prices  Quantity
0 self    Mango     100        10
  other   Mango     120        15
1 self    Apple     150         8
  other   Apple     200         6
2 self   Banana      60        12
  other  Banana      60        24
3 self   Papaya      30        14
  other  Papaya      35        17

### Pivoting

In [13]:
monthly_sales={
    "Product":["Laptop","Mobile","Laptop","Mobile","Laptop","Laptop"],
    "Month":["Jan","Jan","Feb","Feb","Mar","Apr"],
    "Price":[95000,25000,67000,12000,65000,75000]
}

sales=pd.DataFrame(monthly_sales)
sales

#-------Pivoting----------
sales.pivot(
    columns="Month",
    index="Product",
    values="Price"
)

Month        Apr      Feb      Jan      Mar
Product
Laptop   75000.0  67000.0  95000.0  65000.0
Mobile       NaN  12000.0  25000.0      NaN

In [18]:
monthly_sales={
    "Product":["Laptop","Mobile","Laptop","Mobile","Laptop","Laptop","Mobile"],
    "Month":["Jan","Jan","Feb","Feb","Mar","Mar","Feb"],
    "Price":[95000,25000,67000,12000,65000,75000,10000]
}

sales=pd.DataFrame(monthly_sales)
sales

#-------Pivoting----------
sales.pivot_table(
    columns="Month",
    index="Product",
    values="Price",
    aggfunc="sum"
)

Month        Feb      Jan       Mar
Product
Laptop   67000.0  95000.0  140000.0
Mobile   22000.0  25000.0       NaN

### Melting

In [ ]:
shop_sales={
    "Product":["Laptop","Mobile","Mouse"],
    "Jan":[45000,14000,140],
    "Feb":[55000,23000,199],
    "Mar":[56000,12000,149]
}

sales_df=pd.DataFrame(shop_sales)
sales_df.melt(
    id_vars="Product",
    var_name="Month",
    value_name="Price"
)

  Product Month  Price
0  Laptop   Jan  45000
1  Mobile   Jan  14000
2   Mouse   Jan    140
3  Laptop   Feb  55000
4  Mobile   Feb  23000
5   Mouse   Feb    199
6  Laptop   Mar  56000
7  Mobile   Mar  12000
8   Mouse   Mar    149